/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chess.display;

/**
 *
 * @author Chi Nguyen
 */
public class ForgotPasswordForm extends javax.swing.JFrame {
   
    private String dataContructor;
    
    /**
     * Creates new form ForgotPasswordForm
     */
    public ForgotPasswordForm(String dataContructor) {
        initComponents();
        this.dataContructor = dataContructor;
    }

    ForgotPasswordForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtmaxacnhan = new javax.swing.JPasswordField();
        btnconfirm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtcode = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/R.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        txtusername.setText("Username or Email");
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 330, 32));

        txtmaxacnhan.setText("Confirmation code");
        txtmaxacnhan.setEchoChar('\u0000');
        getContentPane().add(txtmaxacnhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 190, 34));

        btnconfirm.setBackground(new java.awt.Color(255, 204, 0));
        btnconfirm.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnconfirm.setText("CONFIRM");
        getContentPane().add(btnconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 492, -1));

        jLabel2.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORGOT PASSWORD");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        txtcode.setText("Password");
        txtcode.setEchoChar('\u0000');
        getContentPane().add(txtcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 130, 34));

        jLabel3.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/den.jpg"))); // NOI18N
        jLabel3.setText("LOG IN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 710, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPasswordForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtcode;
    private javax.swing.JPasswordField txtmaxacnhan;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
