/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chess.display;

/**
 *
 * @author Chi Nguyen
 */
public class formtrangchu extends javax.swing.JFrame {

    private String dataContructor;

    /**
     * Creates new form formtrangchu
     */
    public formtrangchu(String dataContructor) {
        initComponents();
        this.dataContructor = dataContructor;
    }

    formtrangchu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnplay = new javax.swing.JButton();
        btnpuzzles = new javax.swing.JButton();
        btnlearn = new javax.swing.JButton();
        btnwatch = new javax.swing.JButton();
        btnnews = new javax.swing.JButton();
        btnsocial = new javax.swing.JButton();
        btnmore = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        btnsignup = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logom.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 156, 64, 519));

        btnplay.setBackground(new java.awt.Color(0, 0, 0));
        btnplay.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnplay.setForeground(new java.awt.Color(255, 255, 255));
        btnplay.setText("Play");
        btnplay.setBorder(null);
        jPanel1.add(btnplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 90, 40));

        btnpuzzles.setBackground(new java.awt.Color(0, 0, 0));
        btnpuzzles.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnpuzzles.setForeground(new java.awt.Color(255, 255, 255));
        btnpuzzles.setText("Puzzles");
        btnpuzzles.setBorder(null);
        jPanel1.add(btnpuzzles, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 90, 40));

        btnlearn.setBackground(new java.awt.Color(0, 0, 0));
        btnlearn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnlearn.setForeground(new java.awt.Color(255, 255, 255));
        btnlearn.setText("Learn");
        btnlearn.setBorder(null);
        jPanel1.add(btnlearn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 90, 40));

        btnwatch.setBackground(new java.awt.Color(0, 0, 0));
        btnwatch.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnwatch.setForeground(new java.awt.Color(255, 255, 255));
        btnwatch.setText("Watch");
        btnwatch.setBorder(null);
        btnwatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwatchActionPerformed(evt);
            }
        });
        jPanel1.add(btnwatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 90, 40));

        btnnews.setBackground(new java.awt.Color(0, 0, 0));
        btnnews.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnnews.setForeground(new java.awt.Color(255, 255, 255));
        btnnews.setText("News");
        btnnews.setBorder(null);
        jPanel1.add(btnnews, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 90, 40));

        btnsocial.setBackground(new java.awt.Color(0, 0, 0));
        btnsocial.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnsocial.setForeground(new java.awt.Color(255, 255, 255));
        btnsocial.setText("Social");
        btnsocial.setBorder(null);
        btnsocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsocialActionPerformed(evt);
            }
        });
        jPanel1.add(btnsocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 90, 40));

        btnmore.setBackground(new java.awt.Color(0, 0, 0));
        btnmore.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnmore.setForeground(new java.awt.Color(255, 255, 255));
        btnmore.setText("More");
        btnmore.setBorder(null);
        jPanel1.add(btnmore, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, 90, 40));

        btnlogin.setBackground(new java.awt.Color(0, 0, 0));
        btnlogin.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin.setText("LOG IN");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, 160, 40));

        btnsignup.setBackground(new java.awt.Color(0, 0, 0));
        btnsignup.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnsignup.setForeground(new java.awt.Color(255, 255, 255));
        btnsignup.setText("SIGN UP");
        jPanel1.add(btnsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, 160, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dendai.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 830));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(java.awt.Color.darkGray);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/banco.jpg"))); // NOI18N

        jButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Play Online");

        jButton2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Play Computer");

        jLabel5.setFont(new java.awt.Font("Pristina", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PLAY CHESS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel5)
                        .addGap(55, 55, 55)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsocialActionPerformed

    private void btnwatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnwatchActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_btnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formtrangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formtrangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formtrangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formtrangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formtrangchu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlearn;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnmore;
    private javax.swing.JButton btnnews;
    private javax.swing.JButton btnplay;
    private javax.swing.JButton btnpuzzles;
    private javax.swing.JButton btnsignup;
    private javax.swing.JButton btnsocial;
    private javax.swing.JButton btnwatch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
