/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chess.display;

/**
 *
 * @author Chi Nguyen
 */
public class formloggedin extends javax.swing.JFrame {

    /**
     * Creates new form formloggedin
     */
    public formloggedin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnplay = new javax.swing.JButton();
        btnpuzzles = new javax.swing.JButton();
        btnlearn = new javax.swing.JButton();
        btnmore = new javax.swing.JButton();
        btnsocial = new javax.swing.JButton();
        btnnews = new javax.swing.JButton();
        btnwatch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 156, 64, 519));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logom.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnplay.setBackground(new java.awt.Color(0, 0, 0));
        btnplay.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnplay.setForeground(new java.awt.Color(255, 255, 255));
        btnplay.setText("Play");
        btnplay.setBorder(null);
        jPanel1.add(btnplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 90, 40));

        btnpuzzles.setBackground(new java.awt.Color(0, 0, 0));
        btnpuzzles.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnpuzzles.setForeground(new java.awt.Color(255, 255, 255));
        btnpuzzles.setText("Puzzles");
        btnpuzzles.setBorder(null);
        jPanel1.add(btnpuzzles, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 90, 40));

        btnlearn.setBackground(new java.awt.Color(0, 0, 0));
        btnlearn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnlearn.setForeground(new java.awt.Color(255, 255, 255));
        btnlearn.setText("Learn");
        btnlearn.setBorder(null);
        jPanel1.add(btnlearn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 90, 40));

        btnmore.setBackground(new java.awt.Color(0, 0, 0));
        btnmore.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnmore.setForeground(new java.awt.Color(255, 255, 255));
        btnmore.setText("More");
        btnmore.setBorder(null);
        jPanel1.add(btnmore, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 90, 40));

        btnsocial.setBackground(new java.awt.Color(0, 0, 0));
        btnsocial.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnsocial.setForeground(new java.awt.Color(255, 255, 255));
        btnsocial.setText("Social");
        btnsocial.setBorder(null);
        btnsocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsocialActionPerformed(evt);
            }
        });
        jPanel1.add(btnsocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 90, 40));

        btnnews.setBackground(new java.awt.Color(0, 0, 0));
        btnnews.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnnews.setForeground(new java.awt.Color(255, 255, 255));
        btnnews.setText("News");
        btnnews.setBorder(null);
        jPanel1.add(btnnews, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 90, 40));

        btnwatch.setBackground(new java.awt.Color(0, 0, 0));
        btnwatch.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnwatch.setForeground(new java.awt.Color(255, 255, 255));
        btnwatch.setText("Watch");
        btnwatch.setBorder(null);
        btnwatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwatchActionPerformed(evt);
            }
        });
        jPanel1.add(btnwatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 90, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dendai.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 830));

        jPanel2.setBackground(java.awt.Color.darkGray);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsocialActionPerformed

    private void btnwatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnwatchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formloggedin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formloggedin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formloggedin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formloggedin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formloggedin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlearn;
    private javax.swing.JButton btnmore;
    private javax.swing.JButton btnnews;
    private javax.swing.JButton btnplay;
    private javax.swing.JButton btnpuzzles;
    private javax.swing.JButton btnsocial;
    private javax.swing.JButton btnwatch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
